"""Core logic for the Reading Plan delivery worker (COMPANION_SPEC.md §9.2, §15.2).

Triggered every 15 minutes (UTC). For each active (non-paused) enrollment whose
per-user local delivery window matches "now", send that day's reading via the
existing SMS path and record progress. Designed to be:

  * Idempotent  — at most one day delivered per enrollment per local calendar day
                  (guarded by lastDeliveredDay monotonicity + lastDeliveredAt date).
  * Graceful    — one user's failure never aborts the batch; everything is wrapped.
  * Cheap       — verse text is generated by the model best-effort; if the LLM or
                  the OpenAI key is unavailable, a deterministic message is sent.

DELIVERY WINDOW SEMANTICS (assumptions, documented in the integration spec):
  - `deliveryTime` ("HH:MM", default "08:00") is interpreted in the user's local
    timezone (`users.timezone`, IANA; default America/New_York; UTC if unresolved).
  - A day becomes due when local now >= deliveryTime AND nothing was delivered for
    that enrollment yet on the current local date. The 15-min cadence means a day is
    sent within ~15 min of its window opening.
  - The day delivered is `lastDeliveredDay + 1`; once it exceeds the plan's dayCount
    the plan is marked completed and no further sends occur.
"""
import logging
import os
from datetime import datetime, timezone
from decimal import Decimal

import boto3
from boto3.dynamodb.conditions import Key
from botocore.exceptions import ClientError

# Shared layer (/opt/python): SMS send + secrets. Package fallback for local tests.
import sys
sys.path.append("/opt/python")
try:
    from sms_notifications import send_sms
except ImportError:  # pragma: no cover
    try:
        from lambdas.shared.sms_notifications import send_sms
    except ImportError:
        send_sms = None

try:
    from secrets_helper import get_openai_api_key
except ImportError:  # pragma: no cover
    try:
        from lambdas.shared.secrets_helper import get_openai_api_key
    except ImportError:
        get_openai_api_key = lambda: None  # noqa: E731

logger = logging.getLogger()
logger.setLevel(logging.INFO)

_ENV = os.environ.get("ENVIRONMENT", "dev")
_PROJECT = os.environ.get("PROJECT_NAME", "versiful")
DEFAULT_TZ = os.environ.get("DEFAULT_TIMEZONE", "America/New_York")


def _table_name(env_var, suffix):
    return os.environ.get(env_var, f"{_ENV}-{_PROJECT}-{suffix}")


READING_PLANS_TABLE = _table_name("READING_PLANS_TABLE", "reading-plans")
READING_PLAN_DAYS_TABLE = _table_name("READING_PLAN_DAYS_TABLE", "reading-plan-days")
USER_READING_PLANS_TABLE = _table_name("USER_READING_PLANS_TABLE", "user-reading-plans")
USERS_TABLE = _table_name("USERS_TABLE", "users")
VERSE_HISTORY_TABLE = _table_name("VERSE_HISTORY_TABLE", "verse-history")

_dynamodb = boto3.resource("dynamodb")


def _t(name):
    return _dynamodb.Table(name)


def _now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# Timezone / window
# ---------------------------------------------------------------------------
def _resolve_tz(tz_name):
    """Return a tzinfo for the IANA name, falling back to UTC if unresolved."""
    name = tz_name or DEFAULT_TZ
    try:
        from zoneinfo import ZoneInfo
        return ZoneInfo(name)
    except Exception:
        logger.warning("Could not resolve timezone %r; using UTC.", name)
        return timezone.utc


def _parse_hhmm(value, default=(8, 0)):
    try:
        hh, mm = str(value).split(":")
        hh, mm = int(hh), int(mm)
        if 0 <= hh <= 23 and 0 <= mm <= 59:
            return hh, mm
    except (ValueError, AttributeError):
        pass
    return default


def _local_date_of(iso_str, tz):
    """Return the local date for an ISO-8601 string, or None."""
    if not iso_str:
        return None
    try:
        s = iso_str.replace("Z", "+00:00")
        dt = datetime.fromisoformat(s)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(tz).date()
    except (ValueError, TypeError):
        return None


def is_due(enrollment, user, now_utc=None):
    """True if this enrollment's next day is due in the user's local window now."""
    if enrollment.get("status") != "active":
        return False
    now_utc = now_utc or datetime.now(timezone.utc)
    tz = _resolve_tz((user or {}).get("timezone"))
    now_local = now_utc.astimezone(tz)

    hh, mm = _parse_hhmm(enrollment.get("deliveryTime"), default=(8, 0))
    if (now_local.hour, now_local.minute) < (hh, mm):
        return False  # before today's window

    last_local_date = _local_date_of(enrollment.get("lastDeliveredAt"), tz)
    if last_local_date is not None and last_local_date >= now_local.date():
        return False  # already delivered today
    return True


def next_day_number(enrollment):
    return int(enrollment.get("lastDeliveredDay") or 0) + 1


# ---------------------------------------------------------------------------
# Data access
# ---------------------------------------------------------------------------
def scan_active_enrollments():
    """Scan user_reading_plans for active enrollments (small table — spec §4.3)."""
    items, kwargs = [], {}
    while True:
        try:
            resp = _t(USER_READING_PLANS_TABLE).scan(**kwargs)
        except ClientError as e:
            logger.error("scan_active_enrollments failed: %s", e)
            break
        for it in resp.get("Items", []):
            if it.get("status") == "active":
                items.append(it)
        lek = resp.get("LastEvaluatedKey")
        if not lek:
            break
        kwargs["ExclusiveStartKey"] = lek
    return items


def get_user(user_id):
    try:
        return _t(USERS_TABLE).get_item(Key={"userId": user_id}).get("Item")
    except ClientError as e:
        logger.error("get_user(%s) failed: %s", user_id, e)
        return None


def get_plan(slug):
    try:
        return _t(READING_PLANS_TABLE).get_item(Key={"slug": slug}).get("Item")
    except ClientError as e:
        logger.error("get_plan(%s) failed: %s", slug, e)
        return None


def get_plan_day(slug, day_number):
    try:
        return _t(READING_PLAN_DAYS_TABLE).get_item(
            Key={"slug": slug, "dayNumber": Decimal(int(day_number))}
        ).get("Item")
    except ClientError as e:
        logger.error("get_plan_day(%s,%s) failed: %s", slug, day_number, e)
        return None


def mark_delivered(user_id, plan_id, day_number, plan_completed=False):
    expr = (
        "SET lastDeliveredDay = :d, lastDeliveredAt = :now, "
        "currentDay = :cd, updatedAt = :now"
    )
    values = {
        ":d": Decimal(int(day_number)),
        ":cd": Decimal(int(day_number)),
        ":now": _now_iso(),
    }
    names = None
    if plan_completed:
        expr += ", #s = :s, completedAt = :now"
        values[":s"] = "completed"
        names = {"#s": "status"}
    kwargs = dict(
        Key={"userId": user_id, "planId": plan_id},
        UpdateExpression=expr,
        ExpressionAttributeValues=values,
    )
    if names:
        kwargs["ExpressionAttributeNames"] = names
    _t(USER_READING_PLANS_TABLE).update_item(**kwargs)


def record_verse_history(user_id, phone_number, reference, themes, channel="sms"):
    """Best-effort verse_history write (context='reading_plan'). Never raises."""
    try:
        item = {
            "userId": user_id,
            "sentAt": _now_iso(),
            "reference": reference,
            "displayRef": reference,
            "context": "reading_plan",
            "channel": channel,
        }
        if phone_number:
            item["phoneNumber"] = phone_number
        if themes:
            item["themes"] = themes
        _t(VERSE_HISTORY_TABLE).put_item(Item=item)
    except Exception as e:  # pragma: no cover - best effort
        logger.warning("verse_history write failed (non-fatal): %s", e)


# ---------------------------------------------------------------------------
# Message composition
# ---------------------------------------------------------------------------
def generate_devotional(passage_ref, theme, bible_version=None):
    """Best-effort short devotional from the model. Returns text or None.

    Kept tiny and cheap (gpt-4o-mini). Any failure (no key, SDK missing, API error)
    returns None and the caller falls back to a deterministic message.
    """
    try:
        from openai import OpenAI
    except Exception:
        return None
    api_key = None
    try:
        api_key = get_openai_api_key()
    except Exception:
        api_key = None
    if not api_key:
        return None
    version = bible_version or "NIV"
    try:
        client = OpenAI(api_key=api_key)
        prompt = (
            f"Write a warm, 1-2 sentence devotional reflection on {passage_ref} "
            f"(theme: {theme}). Quote the verse briefly in the {version} translation. "
            f"Keep it under 320 characters total. No greeting, no sign-off."
        )
        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=160,
            temperature=0.7,
        )
        text = (resp.choices[0].message.content or "").strip()
        return text or None
    except Exception as e:
        logger.warning("Devotional generation failed (non-fatal): %s", e)
        return None


def compose_message(plan, day, day_number, day_count, bible_version=None, use_llm=True):
    """Build the SMS body for a plan day (deterministic, with optional LLM intro)."""
    title = (plan or {}).get("title", "Reading plan")
    passage_ref = (day or {}).get("passageRef", "")
    theme = (day or {}).get("theme", "")
    plan_prompt = (day or {}).get("prompt", "")

    header = f"\U0001F4D6 {title} — Day {day_number} of {day_count}"

    devotional = None
    if use_llm and passage_ref:
        devotional = generate_devotional(passage_ref, theme, bible_version)

    parts = [header, ""]
    if devotional:
        parts.append(devotional)
    else:
        line = passage_ref
        if theme:
            line += f" — {theme}"
        parts.append(line)
    if plan_prompt:
        parts.append("")
        parts.append(plan_prompt)
    parts.append("")
    parts.append("Reply with your reflection and I'll save it to your journal.")
    return "\n".join(parts).strip()


# ---------------------------------------------------------------------------
# Per-enrollment delivery + batch
# ---------------------------------------------------------------------------
def deliver_one(enrollment, now_utc=None, use_llm=True):
    """Deliver the due day for a single enrollment. Returns an outcome dict.

    outcome status: "sent" | "skipped" | "finished" | "no_phone" | "no_content"
                    | "send_failed" | "error"
    """
    user_id = enrollment.get("userId")
    plan_id = enrollment.get("planId")
    try:
        user = get_user(user_id)
        if not is_due(enrollment, user, now_utc):
            return {"status": "skipped", "userId": user_id, "planId": plan_id}

        plan = get_plan(plan_id)
        day_count = int((plan or {}).get("dayCount") or 0)
        day_number = next_day_number(enrollment)
        if day_count and day_number > day_count:
            # Plan already fully delivered — mark complete if not already.
            if enrollment.get("status") == "active":
                mark_delivered(user_id, plan_id, day_count, plan_completed=True)
            return {"status": "finished", "userId": user_id, "planId": plan_id}

        day = get_plan_day(plan_id, day_number)
        if not day:
            return {"status": "no_content", "userId": user_id, "planId": plan_id,
                    "dayNumber": day_number}

        phone_number = (user or {}).get("phoneNumber")
        channel = enrollment.get("deliveryChannel", "sms")
        if channel == "sms" and not phone_number:
            return {"status": "no_phone", "userId": user_id, "planId": plan_id}

        bible_version = (user or {}).get("bibleVersion")
        body = compose_message(
            plan, day, day_number, day_count or day_number,
            bible_version=bible_version, use_llm=use_llm,
        )

        if send_sms is None:
            logger.error("send_sms unavailable; cannot deliver.")
            return {"status": "send_failed", "userId": user_id, "planId": plan_id}

        sid = send_sms(phone_number, body)
        if not sid:
            # Don't advance — next run retries (idempotent, no double-send).
            return {"status": "send_failed", "userId": user_id, "planId": plan_id,
                    "dayNumber": day_number}

        plan_completed = bool(day_count) and day_number >= day_count
        mark_delivered(user_id, plan_id, day_number, plan_completed=plan_completed)
        record_verse_history(
            user_id, phone_number, day.get("passageRef"),
            [day.get("theme")] if day.get("theme") else None, channel=channel,
        )
        return {
            "status": "sent", "userId": user_id, "planId": plan_id,
            "dayNumber": day_number, "completed": plan_completed, "messageSid": sid,
        }
    except Exception as e:
        logger.error("deliver_one failed for %s/%s: %s", user_id, plan_id, e, exc_info=True)
        return {"status": "error", "userId": user_id, "planId": plan_id, "error": str(e)}


def run_batch(now_utc=None, use_llm=True):
    """Process every active enrollment; aggregate outcome counts. Never raises."""
    now_utc = now_utc or datetime.now(timezone.utc)
    enrollments = scan_active_enrollments()
    logger.info("reading_plan_delivery: scanning %d active enrollments", len(enrollments))

    counts = {}
    outcomes = []
    for enr in enrollments:
        outcome = deliver_one(enr, now_utc=now_utc, use_llm=use_llm)
        counts[outcome["status"]] = counts.get(outcome["status"], 0) + 1
        if outcome["status"] in ("sent", "send_failed", "error", "no_content", "no_phone"):
            outcomes.append(outcome)

    logger.info("reading_plan_delivery counts: %s", counts)
    return {"scanned": len(enrollments), "counts": counts, "outcomes": outcomes}
